// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: oracle/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_562b782cb9ac197e, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_562b782cb9ac197e, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryRandomNumbersRequest struct {
	RequestId int64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (m *QueryRandomNumbersRequest) Reset()         { *m = QueryRandomNumbersRequest{} }
func (m *QueryRandomNumbersRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRandomNumbersRequest) ProtoMessage()    {}
func (*QueryRandomNumbersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_562b782cb9ac197e, []int{2}
}
func (m *QueryRandomNumbersRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRandomNumbersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRandomNumbersRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRandomNumbersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRandomNumbersRequest.Merge(m, src)
}
func (m *QueryRandomNumbersRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRandomNumbersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRandomNumbersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRandomNumbersRequest proto.InternalMessageInfo

func (m *QueryRandomNumbersRequest) GetRequestId() int64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

type QueryRandomNumbersResponse struct {
	Result *RandomNumbersResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (m *QueryRandomNumbersResponse) Reset()         { *m = QueryRandomNumbersResponse{} }
func (m *QueryRandomNumbersResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRandomNumbersResponse) ProtoMessage()    {}
func (*QueryRandomNumbersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_562b782cb9ac197e, []int{3}
}
func (m *QueryRandomNumbersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRandomNumbersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRandomNumbersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRandomNumbersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRandomNumbersResponse.Merge(m, src)
}
func (m *QueryRandomNumbersResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRandomNumbersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRandomNumbersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRandomNumbersResponse proto.InternalMessageInfo

func (m *QueryRandomNumbersResponse) GetResult() *RandomNumbersResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type QueryLastRandomNumbersIdRequest struct {
}

func (m *QueryLastRandomNumbersIdRequest) Reset()         { *m = QueryLastRandomNumbersIdRequest{} }
func (m *QueryLastRandomNumbersIdRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLastRandomNumbersIdRequest) ProtoMessage()    {}
func (*QueryLastRandomNumbersIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_562b782cb9ac197e, []int{4}
}
func (m *QueryLastRandomNumbersIdRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLastRandomNumbersIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLastRandomNumbersIdRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLastRandomNumbersIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLastRandomNumbersIdRequest.Merge(m, src)
}
func (m *QueryLastRandomNumbersIdRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryLastRandomNumbersIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLastRandomNumbersIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLastRandomNumbersIdRequest proto.InternalMessageInfo

type QueryLastRandomNumbersIdResponse struct {
	RequestId int64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (m *QueryLastRandomNumbersIdResponse) Reset()         { *m = QueryLastRandomNumbersIdResponse{} }
func (m *QueryLastRandomNumbersIdResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLastRandomNumbersIdResponse) ProtoMessage()    {}
func (*QueryLastRandomNumbersIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_562b782cb9ac197e, []int{5}
}
func (m *QueryLastRandomNumbersIdResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLastRandomNumbersIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLastRandomNumbersIdResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLastRandomNumbersIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLastRandomNumbersIdResponse.Merge(m, src)
}
func (m *QueryLastRandomNumbersIdResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryLastRandomNumbersIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLastRandomNumbersIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLastRandomNumbersIdResponse proto.InternalMessageInfo

func (m *QueryLastRandomNumbersIdResponse) GetRequestId() int64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "slandymani.odinworkshop.oracle.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "slandymani.odinworkshop.oracle.QueryParamsResponse")
	proto.RegisterType((*QueryRandomNumbersRequest)(nil), "slandymani.odinworkshop.oracle.QueryRandomNumbersRequest")
	proto.RegisterType((*QueryRandomNumbersResponse)(nil), "slandymani.odinworkshop.oracle.QueryRandomNumbersResponse")
	proto.RegisterType((*QueryLastRandomNumbersIdRequest)(nil), "slandymani.odinworkshop.oracle.QueryLastRandomNumbersIdRequest")
	proto.RegisterType((*QueryLastRandomNumbersIdResponse)(nil), "slandymani.odinworkshop.oracle.QueryLastRandomNumbersIdResponse")
}

func init() { proto.RegisterFile("oracle/query.proto", fileDescriptor_562b782cb9ac197e) }

var fileDescriptor_562b782cb9ac197e = []byte{
	// 491 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0x4f, 0x6b, 0xd4, 0x40,
	0x18, 0xc6, 0x37, 0x5a, 0x17, 0x1c, 0x6f, 0xb3, 0x3d, 0x68, 0xd4, 0xb4, 0xe6, 0x50, 0x8a, 0xd2,
	0x0c, 0xdd, 0x1c, 0xa4, 0xbd, 0x54, 0x8b, 0x97, 0x62, 0x11, 0xcd, 0x51, 0x0f, 0x61, 0xb2, 0x19,
	0xd2, 0xc1, 0x64, 0xde, 0x74, 0x66, 0xa2, 0x2e, 0xe2, 0xc5, 0x4f, 0x20, 0xf8, 0x09, 0xfc, 0x36,
	0x05, 0x11, 0x0a, 0x5e, 0x3c, 0x89, 0xec, 0xfa, 0x41, 0xa4, 0x33, 0xb3, 0xd6, 0xac, 0xe9, 0xdf,
	0x5b, 0x98, 0x79, 0x9f, 0xe7, 0xfd, 0x3d, 0xf3, 0xbe, 0x04, 0x61, 0x90, 0x74, 0x54, 0x32, 0xb2,
	0xdf, 0x30, 0x39, 0x8e, 0x6a, 0x09, 0x1a, 0x70, 0xa0, 0x4a, 0x2a, 0xf2, 0x71, 0x45, 0x05, 0x8f,
	0x20, 0xe7, 0xe2, 0x2d, 0xc8, 0xd7, 0x6a, 0x0f, 0xea, 0xc8, 0xd6, 0xfa, 0x8b, 0x05, 0x14, 0x60,
	0x4a, 0xc9, 0xd1, 0x97, 0x55, 0xf9, 0x77, 0x0a, 0x80, 0xa2, 0x64, 0x84, 0xd6, 0x9c, 0x50, 0x21,
	0x40, 0x53, 0xcd, 0x41, 0x28, 0x77, 0x7b, 0x7f, 0x04, 0xaa, 0x02, 0x45, 0x32, 0xaa, 0x5c, 0x33,
	0xf2, 0x66, 0x3d, 0x63, 0x9a, 0xae, 0x93, 0x9a, 0x16, 0x5c, 0x98, 0x62, 0x57, 0x3b, 0x70, 0x4c,
	0x35, 0x95, 0xb4, 0x9a, 0x19, 0xdc, 0x76, 0x87, 0x92, 0x8a, 0x1c, 0xaa, 0x54, 0x34, 0x55, 0xc6,
	0xa4, 0xbb, 0x0c, 0x17, 0x11, 0x7e, 0x71, 0xe4, 0xf9, 0xdc, 0x28, 0x12, 0xb6, 0xdf, 0x30, 0xa5,
	0xc3, 0x57, 0x68, 0xd0, 0x3a, 0x55, 0x35, 0x08, 0xc5, 0xf0, 0x13, 0xd4, 0xb7, 0xce, 0x37, 0xbd,
	0x65, 0x6f, 0xf5, 0xc6, 0x70, 0x25, 0x3a, 0x3d, 0x6f, 0x64, 0xf5, 0xdb, 0x0b, 0x07, 0x3f, 0x97,
	0x7a, 0x89, 0xd3, 0x86, 0x9b, 0xe8, 0x96, 0x31, 0x4f, 0x0c, 0xcf, 0x33, 0x8b, 0xe3, 0x3a, 0xe3,
	0xbb, 0x08, 0x49, 0xfb, 0x99, 0xf2, 0xdc, 0xb4, 0xb9, 0x9a, 0x5c, 0x77, 0x27, 0x3b, 0x79, 0xc8,
	0x91, 0xdf, 0xa5, 0x75, 0x7c, 0x4f, 0x51, 0x5f, 0x32, 0xd5, 0x94, 0xda, 0xf1, 0xc5, 0x67, 0xf1,
	0xcd, 0xdb, 0x34, 0xa5, 0x4e, 0x9c, 0x45, 0x78, 0x0f, 0x2d, 0x99, 0x56, 0xbb, 0x54, 0xe9, 0x56,
	0xdd, 0x4e, 0x3e, 0x7b, 0xa6, 0xc7, 0x68, 0xf9, 0xe4, 0x12, 0xc7, 0x74, 0x7a, 0xa0, 0xe1, 0xd7,
	0x05, 0x74, 0xcd, 0x78, 0xe0, 0x2f, 0x1e, 0xea, 0xdb, 0xf7, 0xc2, 0xc3, 0xb3, 0xb8, 0xff, 0x1f,
	0x99, 0x1f, 0x5f, 0x48, 0x63, 0xe1, 0xc2, 0xe8, 0xe3, 0xf7, 0xdf, 0x9f, 0xaf, 0xac, 0xe2, 0x15,
	0x72, 0x2c, 0x26, 0xff, 0x8a, 0x49, 0x6b, 0xa1, 0xf0, 0x37, 0x0f, 0x0d, 0x3a, 0xde, 0x0c, 0x6f,
	0x9c, 0xab, 0x79, 0xd7, 0xc0, 0xfd, 0xcd, 0xcb, 0x48, 0x1d, 0xfe, 0x96, 0xc1, 0xdf, 0xc0, 0x0f,
	0x3b, 0x99, 0xdb, 0xfb, 0x9e, 0xda, 0xb1, 0x92, 0xf7, 0xc7, 0xd3, 0xf8, 0x60, 0xf2, 0x74, 0x0c,
	0x0f, 0x6f, 0x9d, 0x0b, 0xea, 0xe4, 0xcd, 0xf0, 0x1f, 0x5d, 0xde, 0xc0, 0x65, 0x8b, 0x4d, 0xb6,
	0x35, 0xfc, 0xa0, 0x33, 0x5b, 0x49, 0x95, 0x4e, 0xe7, 0x02, 0xf2, 0x7c, 0x7b, 0xf7, 0x60, 0x12,
	0x78, 0x87, 0x93, 0xc0, 0xfb, 0x35, 0x09, 0xbc, 0x4f, 0xd3, 0xa0, 0x77, 0x38, 0x0d, 0x7a, 0x3f,
	0xa6, 0x41, 0xef, 0xe5, 0xb0, 0xe0, 0x7a, 0xaf, 0xc9, 0xa2, 0x11, 0x54, 0xf3, 0xb3, 0x5e, 0xfb,
	0x6b, 0xfe, 0x6e, 0x66, 0xaf, 0xc7, 0x35, 0x53, 0x59, 0xdf, 0xfc, 0x22, 0xe2, 0x3f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x32, 0x97, 0xe0, 0x12, 0xea, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// RandomNumbersResult defines a rpc handler method for MsgRandomNumbersData.
	RandomNumbersResult(ctx context.Context, in *QueryRandomNumbersRequest, opts ...grpc.CallOption) (*QueryRandomNumbersResponse, error)
	// LastRandomNumbersId query the last RandomNumbers result id
	LastRandomNumbersId(ctx context.Context, in *QueryLastRandomNumbersIdRequest, opts ...grpc.CallOption) (*QueryLastRandomNumbersIdResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/slandymani.odinworkshop.oracle.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RandomNumbersResult(ctx context.Context, in *QueryRandomNumbersRequest, opts ...grpc.CallOption) (*QueryRandomNumbersResponse, error) {
	out := new(QueryRandomNumbersResponse)
	err := c.cc.Invoke(ctx, "/slandymani.odinworkshop.oracle.Query/RandomNumbersResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LastRandomNumbersId(ctx context.Context, in *QueryLastRandomNumbersIdRequest, opts ...grpc.CallOption) (*QueryLastRandomNumbersIdResponse, error) {
	out := new(QueryLastRandomNumbersIdResponse)
	err := c.cc.Invoke(ctx, "/slandymani.odinworkshop.oracle.Query/LastRandomNumbersId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// RandomNumbersResult defines a rpc handler method for MsgRandomNumbersData.
	RandomNumbersResult(context.Context, *QueryRandomNumbersRequest) (*QueryRandomNumbersResponse, error)
	// LastRandomNumbersId query the last RandomNumbers result id
	LastRandomNumbersId(context.Context, *QueryLastRandomNumbersIdRequest) (*QueryLastRandomNumbersIdResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) RandomNumbersResult(ctx context.Context, req *QueryRandomNumbersRequest) (*QueryRandomNumbersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RandomNumbersResult not implemented")
}
func (*UnimplementedQueryServer) LastRandomNumbersId(ctx context.Context, req *QueryLastRandomNumbersIdRequest) (*QueryLastRandomNumbersIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LastRandomNumbersId not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/slandymani.odinworkshop.oracle.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RandomNumbersResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRandomNumbersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RandomNumbersResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/slandymani.odinworkshop.oracle.Query/RandomNumbersResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RandomNumbersResult(ctx, req.(*QueryRandomNumbersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LastRandomNumbersId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLastRandomNumbersIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LastRandomNumbersId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/slandymani.odinworkshop.oracle.Query/LastRandomNumbersId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LastRandomNumbersId(ctx, req.(*QueryLastRandomNumbersIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "slandymani.odinworkshop.oracle.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "RandomNumbersResult",
			Handler:    _Query_RandomNumbersResult_Handler,
		},
		{
			MethodName: "LastRandomNumbersId",
			Handler:    _Query_LastRandomNumbersId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oracle/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryRandomNumbersRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRandomNumbersRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRandomNumbersRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RequestId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.RequestId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryRandomNumbersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRandomNumbersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRandomNumbersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Result != nil {
		{
			size, err := m.Result.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryLastRandomNumbersIdRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLastRandomNumbersIdRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLastRandomNumbersIdRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryLastRandomNumbersIdResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLastRandomNumbersIdResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLastRandomNumbersIdResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RequestId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.RequestId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryRandomNumbersRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RequestId != 0 {
		n += 1 + sovQuery(uint64(m.RequestId))
	}
	return n
}

func (m *QueryRandomNumbersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Result != nil {
		l = m.Result.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryLastRandomNumbersIdRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryLastRandomNumbersIdResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RequestId != 0 {
		n += 1 + sovQuery(uint64(m.RequestId))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRandomNumbersRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRandomNumbersRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRandomNumbersRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestId", wireType)
			}
			m.RequestId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRandomNumbersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRandomNumbersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRandomNumbersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Result == nil {
				m.Result = &RandomNumbersResult{}
			}
			if err := m.Result.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLastRandomNumbersIdRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLastRandomNumbersIdRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLastRandomNumbersIdRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLastRandomNumbersIdResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLastRandomNumbersIdResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLastRandomNumbersIdResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestId", wireType)
			}
			m.RequestId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
